{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alertmanager-graph-bridge.secretName" . }}
  labels:
    {{- include "alertmanager-graph-bridge.labels" . | nindent 4 }}
type: Opaque
stringData:
  clientSecret: {{ .Values.secret.clientSecret | quote }}
  bearerToken: {{ .Values.secret.bearerToken | quote }}
{{- end }}
